# Generated by Django 5.2.4 on 2025-07-09 22:15

import archives.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    # pyrefly: ignore  # bad-override
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Код ссылки"
                    ),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=128, verbose_name="Пароль"),
                ),
                (
                    "max_downloads",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Макс. скачиваний"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="Скачиваний"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=archives.models.default_expiry, verbose_name="Истекает"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/", verbose_name="Файл")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="archives.archive",
                    ),
                ),
            ],
        ),
    ]
