# Generated by Django 5.2.4 on 2025-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="archive",
            name="zip_file",
            field=models.FileField(blank=True, null=True, upload_to="zips/"),
        ),
    ]
