# Generated by Django 5.2.4 on 2025-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
