# Generated by Django 5.2.4 on 2025-07-12 21:46

import archives.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0002_archive_ready_archive_zip_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="archive",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="archive",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="archive",
            name="expires_at",
            field=models.DateTimeField(default=archives.models.default_expiry),
        ),
        migrations.AlterField(
            model_name="archive",
            name="max_downloads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="archive",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="archive",
            name="short_code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="fileitem",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="fileitem",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="ClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("referer", models.URLField(blank=True)),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="archives.archive",
                    ),
                ),
            ],
        ),
    ]
