# Generated by Django 5.2.4 on 2025-07-17 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "archives",
            "0003_alter_archive_created_at_alter_archive_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clicklog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
