# Generated by Django 5.2.4 on 2025-07-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0003_alter_archive_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="qr_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="qr_codes/", verbose_name="QR-код"
            ),
        ),
    ]
