# Generated by Django 5.2.4 on 2025-07-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0004_archive_qr_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="password",
            field=models.CharField(
                blank=True, help_text="Hashed archive password", max_length=128
            ),
        ),
    ]
