# Generated by Django 5.2.4 on 2025-07-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0005_alter_archive_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="name",
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
