# Generated by Django 5.2.4 on 2025-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0005_archive_owner_alter_archive_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
