# Generated by Django 5.2.4 on 2025-07-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0006_alter_archive_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
