# Generated by Django 5.2.4 on 2025-07-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0007_archive_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="build_task_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
