services:
  db:
    image: postgres:16-alpine
    container_name: default-db
    environment:
      POSTGRES_DB: zipshare
      POSTGRES_USER: zipshare
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zipshare"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: default-redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: default-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    depends_on:
      - redis

  worker:
    build: .
    container_name: default-worker
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    environment:
      DJANGO_DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: ["celery", "-A", "config", "beat", "-l", "info"]
    depends_on:
      - redis
      - db
    env_file: .env
    volumes:
      - ./:/app

  cronworker:
    build: .
    command: ["celery", "-A", "config", "worker", "-l", "info", "-Q", "celery"]
    depends_on:
      - redis
      - db
    env_file: .env
    volumes:
      - ./:/app


volumes:
  db_data:
