apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-worker
spec:
  replicas: 1
  selector:
    matchLabels: { app: default-worker }
  template:
    metadata:
      labels: { app: default-worker }
    spec:
      containers:
      - name: worker
        image: default-worker:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: web-config
        - secretRef:
            name: django-secret
        env:
        - name: DATABASE_URL
          value: >-
            postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)
            @$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
        - name: REDIS_URL
          value: redis://redis:6379/0
