apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  DJANGO_DEBUG: "True"
  DJANGO_SECRET_KEY: "your-secret-key"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_DB: default
  POSTGRES_USER: default
  POSTGRES_PASSWORD: secret
