apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "default.shiz,myapp.local"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"