apiVersion: apps/v1
kind: Deployment
metadata: { name: worker }
spec:
  selector: { matchLabels: { app: worker } }
  replicas: 1
  template:
    metadata: { labels: { app: worker } }
    spec:
      containers:
      - name: worker
        image: default:latest
        command: ["python","-m","celery","-A","config","worker","--loglevel=info"]
        envFrom:
        - configMapRef: { name: web-config }
        - secretRef:    { name: db-secret }
        volumeMounts:
        - name: media
          mountPath: /vol/web/media
      volumes:
      - name: media
        emptyDir: {}
